# Generated by Django 4.2 on 2023-04-18 17:27

import cars.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название авто')),
                ('year', models.IntegerField(validators=[cars.validators.validate_year], verbose_name='Год выпуска')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='photos/default.jpg', null=True, upload_to='photos/', verbose_name='Фото автомобиля')),
                ('car', models.ForeignKey(blank=True, default='photos/default.jpg', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images', to='cars.car')),
            ],
        ),
    ]
